-- phpMyAdmin SQL Dump
-- version 3.3.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 15, 2013 at 01:13 PM
-- Server version: 5.5.8
-- PHP Version: 5.3.5

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `site`
--

-- --------------------------------------------------------

--
-- Table structure for table `conect`
--

CREATE TABLE IF NOT EXISTS `conect` (
  `Nume` varchar(15) NOT NULL,
  `Parola` varchar(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `conect`
--

INSERT INTO `conect` (`Nume`, `Parola`) VALUES
('ardnaxela', 'parola');

-- --------------------------------------------------------

--
-- Table structure for table `filme1`
--

CREATE TABLE IF NOT EXISTS `filme1` (
  `id_film` int(4) NOT NULL AUTO_INCREMENT,
  `an_aparitie` int(11) DEFAULT NULL,
  `titlu` tinytext,
  `descriere` text,
  `gen_film` text NOT NULL,
  `trailer` text NOT NULL,
  `imagine` text NOT NULL,
  `pret` mediumint(8) unsigned NOT NULL,
  PRIMARY KEY (`id_film`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=35 ;

--
-- Dumping data for table `filme1`
--

INSERT INTO `filme1` (`id_film`, `an_aparitie`, `titlu`, `descriere`, `gen_film`, `trailer`, `imagine`, `pret`) VALUES
(1, 2012, 'Mizerabilii', ' Mizerabilii este considerat drept una dintre capodoperele umanitatii, precum si o adevarata fresca sociala.\r\n', 'muzical', 'EkHHHUk8RCw', 'http://ecx.images-amazon.com/images/I/51M1TsXn16L._SL500_AA300_.jpg', 10),
(2, 2012, 'Juramantul (The Vow)', 'Paige (interpretata de Rachel McAdams) si Leo (interpretat de Channing Tatum) sunt casatoriti si se iubesc la nebunie. Ambii sunt artisti de succes in Chicago. Intr-o noapte cu ninsoare deasa, cei doi sunt victimele unui accident de masina. Leo scapa nevatamat, insa Paige are leziuni cerebrale, care ii sterg din memorie toate amintirile legate de relatia cu sotul sau. La iesirea din coma, Leo este pentru ea un strain.', 'dragoste', '8swF2-R6X9A', 'http://ecx.images-amazon.com/images/I/51KVkBxgm6L._SL500_AA300_.jpg', 11),
(3, 1994, 'Forrest Gump', 'Viata este ca o cutie de ciocolata... nu stii niciodata cu ce te alegi.', 'comedie', 'P0oNzk3LhHk', 'http://o.scdn.co/300/94c4aa21dbe708160bb6bcd4942a8efa657ce803', 13),
(4, 2010, 'Inception (Inceputul)', 'Leonardo DiCaprio este Dom Cobb, un hot desavarsit, un adevarat artist in domeniul revolutionar al extractiei, adica al furtului de informatii pretioase din mintile celor care dorm.', 'actiune', '8hP9D6kZseM', 'http://o.scdn.co/300/ff0f574924386e6c116794de2abf66e260c8be0c', 8),
(5, 2002, 'Ice Age', 'Acum 20 000 de ani, P&#227;mântul era o planet&#227; plin&#227; de amenint&#227;ri. Una dintre acestea era începerea Epocii de Gheat&#227;. Pentru a se pune la ad&#227;post de înghet, animalele care populau P&#227;mântul la acea vreme încep s&#227; migreze spre sud. Exceptie fac un mamut pe nume Manfred, obisnuit s&#227; fac&#227; totul în maniera sa personal&#227; si un lenes pe nume Sid, obisnuit s&#227; nu fac&#227; niciodat&#227; nimic. ', 'comedie', 'VsvaFxkXrbg', 'http://stafidutz.net/wp-content/uploads/2011/11/Ice_Age_2002_Cartoons.jpg', 15),
(6, 2012, 'Rise of the Guardians', 'Mos Craciun (Alec Baldwin), Iepurasul de Paste (Hugh Jackman), Jack Frost (Chris Pine), si Zana Maseluta (Isla Fisher), isi aduna puterile si se unesc pentru a-l opri pe Boogeyman (Jude Law), care si-a pus in cap sa arunce lumea intr-un intuneric total, inspirand frica in gandurile si imaginatia copiilor din lumea intreaga. Premiera filmului pe marile ecrane americane are loc pe data de 21 noiembrie 2012, si va fi distribuit in cinematografe de Paramount Pictures.', 'animatie', 'vWs0qulZ00I', 'http://extras.mnginteractive.com/live/media/site20/2012/1206/20121206_101114_rise-of-the-guardians-movie-quotes_300.jpg', 0),
(7, 2012, 'Frankenweenie ', '         Viktor Frankenstein este un baiat pasionat de arta regizarii si ajutat de catelul lui Sparky, un Bull Terrier produce filme cu monstrii. Din pacate catelusul Sparky este calcat de masina, da Viktor, inspirat de o lectie invatata la scoala, ii aplica electrosocuri catelului in speranta ca il va salva.', 'animatie', 'XBfcGLBJ2Uc', 'http://ecx.images-amazon.com/images/I/51jT66oYYQL._SL500_AA300_.jpg', 20),
(8, 2012, 'Brave (Neinfricata)', 'Actiunea din “Brave” e plasata in tinuturile de sus, mistice, ale Scotiei, unde Merida e o printesa in regatul condus de Regele Fergus (Billy Connolly) si Regina Elinor (Emma Thompson). Ea e o fiica neascultatoare si un foarte bun arcas. Merida sfideaza obiceiurile sacre ale tarii si determina harababura in tot regatul. In incercarea de a indrepta lucrurile, Merida cauta ajutor de la o batrana excentrica – Femeia Inteleapta (Julie Walters) si i se îndeplineste o dorinta nepotrivita.', 'animatie', 'TEHWDA_6e3M', 'http://cdn01.cdn.justjared.com/wp-content/uploads/headlines/2012/06/brave-tops-box-office.jpg', 20),
(9, 1990, 'Home Alone (Singur acasa)', 'Kevin este un baietel de 8 ani ce este lasat din greseala singur acasa de parintii sai, plecati cu restul familiei intr-o vacanta de Craciun la Paris. La inceput, lui Kevin ii place sa stea singur, dar ulterior realizeaza ca lucrurile nu sunt asa simple cum par. Mai ales din momentul in care doi hoti hotarasc sa-i sparga casa. Dar, Kevin nu se sperie asa de usor si hotaraste sa-si apere casa cu orice pret. ', 'comedie', 'sHbo6zjTW6s', 'http://theseconddisc.files.wordpress.com/2010/12/home-alone-ost.jpg', 15),
(10, 1997, 'Titanic', 'Brock Lovett este un cautator de comori si incearca sa recupereze vechi artefacte impreuna cu echipa sa de pe epava Titanicului, un vapor urias care s-a scufundat in Oceanul Atlantic in 1912, dupa ce s-a izbit de un iceberg. Lovett cauta diamante si pietre pretioase, dar descopera un portret al unei tinere fete care nu poarta altceva decat un colier. Cand Rose, in varsta de 102 ani, spune ca ea este tanara din portret, actiunea se muta in 1912 in Southampton, unde pasagerii se urcau la bordul navei Titanic. Printre ei se aflau tanarul Jack Dawson si Rose DeWitt Bukater, care se intorcea in Philadelphia cu logodnicul ei, Cal Hockley, un instarit om de afaceri. In timpul calatoriei, Rose se indragosteste de Jack, iar Cal incearca sa se razbune. Intre timp, Titanicul se ciocneste de un iceberg si apa navaleste in compartimentele din fata. Cal continua sa-i urmareasca pe Jack si pe Rose, iar in tot acest timp uriasa nava isi incepe coborarea catre adancurile oceanului.', 'romantic', 'zCy5WQ9S4c0', 'http://ecx.images-amazon.com/images/I/5114IKlT80L._SL500_AA300_.jpg', 20),
(11, 2010, 'The Walking Dead', '"The Walking Dead" spune povestea lumii de dupa o apocalipsa a mortilor-vii si urmareste aventurile unui grup de supravietuitori care calatoresc prin Statele Unite in cautarea unui nou camin, departe de hoardele de zombi. Grupul este condus de Rick Grimes, fost ofiter de politie. Pe masura ce situatia devine tot mai disperata, grupul este impins sa faca orice pentru a ramane in viata.', 'drama', 'R1v0uFms68U', 'https://twimg0-a.akamaihd.net/profile_images/2323746314/w5ejx2gxy8qbnoooi5sv.jpeg', 20),
(12, 2012, 'Skyfall (Cazut din cer)', 'Agentul James Bond revine in Skyfall, al 23-lea film din cea mai longeviva franciza a tuturor timpurilor. Loialitatea lui Bond fata de M este testata cand trecutul ei se intoarce si o bantuie. Cand MI6 este atacat, 007 trebuie sa gaseasca si sa inlature amenintarea, indiferent de cat de personale sunt pierderile.', 'actiune', '6kw1UVovByw', 'http://i979.photobucket.com/albums/ae273/mikkisays/mikkisays5/ScoreThomasNewman-SkyfallOST-2012MP3320kbps-1.jpg', 35),
(13, 2008, 'Mirrors (Oglinzi malefice)', 'Remake al unui film japonez, "Mirrors" este un horror terifiant ce il are in centrul actiunii pe Ben Carson, un fost politist care lucreaza acum ca agent de paza la un imens magazin universal, inchis multa vreme din cauza unui incediu devastator in care si-au pierdut viata foarte multi angajati. In scurt timp, Ben isi da seama ca magazinul este tinta demonstrantilor care doresc compensatii materiale pentru daunele suferite in timpul cumplitei tragedii si totodata locul in care se petrec decese inexplicabile si in care pare sa bantuie un spirit malefic. ', 'groaza', 'c7byl_mAaOE', 'http://download-movie-soundtracks.com/wp-content/uploads/2010/07/mirrors-soundtrack.jpg', 29),
(14, 2010, 'Despicable Me (Sunt un mic ticalos) ', 'Dupa ce si-a castigat renumele de cel mai talentat hot de pe planeta, Gru constata ca trebuie sa infrunte o concurenta puternica venita din partea tanarului Victor, cel care si-a insusit o arma performanta pentru a duce la bun sfarsit planul indraznet de a fura Luna de pe cer. Dorind sa isi consolideze statutul de cel mai bun hot subtilizand el insusi astrul noptii, Gru adopta temporar trei fetite de la un orfelinat cu scopul de a le forta sa patrunda prin viclesug in locuinta securizata a lui Victor si a-i ajuta astfel pe el si pe loialii lui minioni sa intre in posesia sofisticatei arme.', 'animatie', 'RXZY_XRjABs', 'http://ia.media-imdb.com/images/M/MV5BMTY3NjY0MTQ0Nl5BMl5BanBnXkFtZTcwMzQ2MTc0Mw@@._V1._SY317_CR0,0,214,317_.jpg', 50),
(15, 2010, 'Dear John (Draga John)', 'Acest film, in regia lui Lasse Hallstrom, spune povestea unui tanar soldat care se indragosteste de o studenta idealista. Intr-o vacanta de primavara, Savannah Curtis il intalneste pe John Tyree, aflat intr-o scurta permisie. Pentru personajul lui Chaning Tatum, momentul intalnirii reprezinta dragoste la prima vedere. In urmatorii sapte ani cei doi corespondeaza intens, scrisorile lui Savannah (Amanda Seyfried) insemnand pentru tanarul soldat mai mult decat niste simple gesturi romantice, caci la fiecare misiune periculoasa acesta reuseste sa-si mentina echilibrul pishic tocmai cu ajutorul acestori dovezi de dragoste.', 'romantic', 'NLkTKkNXDp4', 'http://download-movie-soundtracks.com/wp-content/uploads/2010/02/Dear-John-soundtrack.jpg', 45),
(16, 2012, 'The Words ', 'Thriller-ul cu accente dramatice are in centru un scriitor care, in momentul de varf al succesului sau literar, realizeaza care este pretul pe care trebuie sa il plateasca pentru faptul ca a furat opera altui autor .', 'drama', 'gjmrDDD9o_k', 'http://1.bp.blogspot.com/-Cc3uyUNkK-k/UMdrwnDldwI/AAAAAAAAD9o/ZjTstIhGzy0/s1600/1.jpg', 23),
(17, 2012, 'The Hunger Games (Jocurile foamei)', 'O are in centrul actiunii pe Katniss Everdeen, o adolescenta în varsta de 16 ani, care o substituie pe sora ei mai mica Primrose intr-o competitie transmisa in direct la televizor si intitulata "Jocurile Foamei", in care 24 de copii cu varste cuprinse intre 12 ani si 18 ani sunt constransi sa devina gladiatori si sa lupte in arena unii impotriva celorlalti pana la moarte, unul singur dintre ei iesind invingator si intorcandu-se viu si nevatamat acasa.', 'actiune', 'SMGRhAEn6K0', 'http://www.roughstock.com/v2/images/The-Hunger-Games-2012-300-01.jpg', 20),
(18, 2010, 'Alice in Wonderland (Alice in Tara Minuninlor)', 'O tanara de 19 ani se pregateste pentru o petrecere in inalta societate. Ea afla ca mama ei doreste sa ii aranjeze o nunta cu unul dintre nobilii prezenti la eveniment. Alice fuge de la petrecere, urmarind un iepure alb. Ea intra intr-o gaura si ajunge in Tara Minunilor, un loc pe care l-a vizitat in urma cu 10 ani, dar nu-si aminteste. Printre cei care ii uraza "bun venit inapoi" sunt Palarierul Nebun, Tweedledee si Tweedledum si Pisica de Chesire. Alice porneste intr-o calatorie extraordinara pentru a-si clarifica viitorul si pentru a opri dominatia violenta a Reginei Rosii. ', 'aventura', '9POCgSRVvf0', 'http://d2oz5j6ef5tbf6.cloudfront.net/cd/large/Alice_wonderland_D000490002.jpg', 32),
(19, 2011, 'Drive (Cursa)', 'Pilotul e un tip enigmatic cu o viata dubla. Shannon (Bryan Cranston) este agentul Pilotului atat pe timpul zilei, cat si pe timpul noptii. Ziua Pilotul concureaza, iar noaptea participa la jafuri. Ca orice mafiot de talie mica, Shannon are un plan pentru Pilot: constructia unei masini cu care acesta sa poata concura pe un circuit profesionist.', 'drama', 'CWX34ShfcsE', 'http://botosaneni.ro/wp-content/uploads/2012/01/drive-film1-300x300.jpg', 13),
(20, 1972, 'The Godfather (Nasul)', 'Inspirat de romanul lui Mario Puzo, filmul este povestea grandioasa a lui Don Vito Corleone, un mafiot din Sicilia, ajuns cap al unei importante retele mafiote in America. Filmul prezinta o viziune extrem de realista a acestei lumi mai putin accesibile unde cuvantul dat si promisiunile facute au o valoare capitala, iar onoarea este la mare pret. Din pacate pentru el, in momentul in care viata ii este pusa in pericol, copii sai nu mai pot sa stea departe de pericole, fiind antrenati si ei in acest joc extrem de riscant al luptelor intre clanurile mafiote din America.', 'crima', 'vjPmaneLadQ', 'http://www.rhythmhouse.in/ProdImages/images/F065783.jpg', 49),
(21, 2009, 'Avatar', 'Avatar spune povestea unui veteran de razboi pe nume Jake, care este trimis intr- o colonie umana pe o planeta indepartata numita Pandora. Scopul acestei baze este de a extrage si de a folosi cat mai multe dintre resursele minerale foarte numeroase ale planetei.', 'aventura', '5PSNL1qE6VY', 'http://upload.wikimedia.org/wikipedia/en/5/5c/Avatar_picture.jpg', 24),
(22, 2010, 'Tangled', 'Fiind rapita din castelul parintilor ei de catre Mother Gothel pe vremea cand era doar o copila in leagan fiindca parul ei fermecat are capacitatea de a asigura tineretea vesnica si de a vindeca orice rana ori de cate ori fata canta o melodie, frumoasa si rebela printesa Rapunzel si-a petrecut ultimii 18 ani inchisa intr-un turn inalt, la care nu se poate ajunge pe nicio scara. ', 'animatie', 'sSx1dYJlJh4', 'http://ecx.images-amazon.com/images/I/51bqdd9qEIL._SL500_AA300_.jpg', 50),
(23, 2012, 'Step Up Revolution', 'Emily este fiica a unui om de afaceri bogat, care vine la Miami ca sa devina dansatoare profesionista. Ea se indragosteste de Sean, un tanar care este liderul unei trupe de dans intitulata MOB. Acestia doresc sa castige un concurs pentru a obtine o sponsorizare importanta, dar tatal lui Emily are planuri sa transforme cartierul in care isi desfasoara activitatea trupa si concendiaza sute de angajati. Emily se alatura lui Sean si trupei MOB pentru a protesta si risca cu totii sa isi destrame visurile luptand pentru o cauza mareata. ', 'muzical', 'gdamC7jUrjs', 'http://1.bp.blogspot.com/-sptyFsfSZMk/UJU9nvTYxyI/AAAAAAAAAqY/mlqRlGJOXYA/s640/step-up-revolution-exclusive-clip.jpg', 20),
(24, 2000, 'Dancer in the Dark (Dansand cu noaptea)', 'Selma a emigrat, in 1964, impreuna cu baietelul ei, din Cehoslovacia spre America. Acolo isi gaseste de lucru intr-o fabrica si lupta din rasputeri sa-si salveze fiul de la boala care o macina pe ea si care o va duce la orbire. Ea cauta sa puna bani deoparte pentru operatia fiului ei. Adevaratul cosmar incepe insa cand un vecin o acuza pe nedrept ca i-a furat economiile din casa si risca sa fie inchisa, iar baiatul sa ramana singur.', 'muzical', '53vr9EiOH7g', 'http://ecx.images-amazon.com/images/I/513Pj7%2BKLRL._SL500_AA300_.jpg', 10),
(25, 2008, 'The Dark Knight (Cavalerul negru)', 'Actiunea filmului se petrece la un an dupa ce Batman l-a eliminat pe Ra''s Al Ghul. Bruce Wayne si alter-ego-ul sau - Batman, continua sa stabileasca ordinea in Gotham City, alaturi de locotententului James Gordon si Harvey Dent noul procuror districtual. Totul merge bine pentru o vreme iar Batman spera ca in curand Dent ii va lua locul si va deveni urmatorul protector al orasului. Planurile lui Batman sunt spulberate cand un nou pericol ameninta orasul iar locuitorii au nevoie mai mult ca oricand de eroul lor.', 'drama', 'g8evyE9TuYk', 'http://o.scdn.co/300/03cebfd7a52d7a73b886505313cd85d8e1ddeef5', 60),
(26, 2011, 'The Intouchables (Intangibilii)', 'O prietenie imprevizibila, dar cu atat mai sincera, se naste intre Driss si Philippe, doi oameni care nu au nimic in comun. Driss e un barbat de culoare, imigrant din Senegal, care a trait pe la periferia Parisului si care nu de mult timp a iesit din inchisoare, iar Philippe e un artistocrat bogat, meloman si pasionat de arte plastice, ramas paralizat de la brau in jos dupa un accident in timpul zborului cu parapanta. Cei doi ajung sa-si petreaca timpul impreuna cand Driss e angajat sa aiba grija de Philippe. ', 'comedie', '34WIbmXkewU', 'http://o.scdn.co/300/4d699eb1d5599aac042e1d6cc4da7a3d7299c77d', 20),
(27, 2011, 'The artist (Artistul)', ' Povestea il are in centru pe un megastar al filmelor mute, George Valentin, care decade odata cu aparitia sonorului in cinematografie, fiindca nu vrea sa se adapteze si sa-si foloseasca vocea. Peppy, o tanara sic, se nimereste sa fie chiar in fata usii cinematografului in care George Valentin isi lanseaza noul film, iar cand acesta iese sa intalneasca publicul, se ciocneste de ea. Prins de moment, starul o saruta pe obraz pe frumoasa necunoscuta, iar a doua zi poza lor apare in ziar sub titlul mare "Cine e fata?".', 'dragoste', 'OK7pfLlsUQM', 'http://acloserlisten.files.wordpress.com/2012/01/theartist.jpg', 30),
(28, 2012, 'Life of Pi (Viata lui Pi)', 'Dupa naufragiul unui transatlantic, fiul adolescent al unui director de gradina zoologica, Pi Patel, pluteste in deriva intr-o barca de salvare alaturi de 4 animale: un urangutan, o hiena, o zebra ranita si un tigru bengalez. Pustiul isi foloseste cunostintele enciclopedice pentru a-l tine la distanta pe tigrul Richard Parker. Calatorind luni de zile pe ocean, se naste o prietenie intre el si animale.\r\n\r\n', 'aventura', 'mZEZ35Fhvuc', 'http://cdn.songonlyrics.com/soundtracks/wp-content/uploads/2012/10/Life-of-Pi-Soundtrack.jpg', 28),
(29, 1965, 'The Sound of Music (Sunetul muzicii)', 'Bazat pe memoriile Mariei Trapp care au inspirat si musicalul omonim, filmul prezinta povestea unei tinere austriece care in anii ''30 paraseste manastirea in care fusese educata, in dorinta de a se face utila in lumea de afara. Ea este trimisa de calugarite sa indeplineasca rolul de guvernanta a celor sapte copii ai capitanului Georg Von Trapp care, vaduv fiind si mai mereu plecat, nu poate face fata singur educatiei copiilor sai.', 'muzical', 'lEcKXr3mJ_o', 'http://d2oz5j6ef5tbf6.cloudfront.net/cd/large/Sound_Of_Music_Fox426702.jpg', 15),
(30, 2004, 'The Polar Express ', 'Mai exista oare copii care sa nu creada in Mos Craciun? Iata ca eroul nostru nu crede. In timp ce sora lui asteapta cu nerabdare cadourile, baiatul sta linistit in pat, asteptand si el sosirea mosului, pentru a se convinge odata pentru totdeauna ca acesta exista. La doisprezece fara cinci minute, un tren, Polar Expres, opreste in fata casei sale, tren care il va duce pana la Polul Nord, acolo unde traieste mosul. ', 'aventura', 'GNno8AdXSF8', 'http://ecx.images-amazon.com/images/I/517Y3SCt63L._SL500_AA300_.jpg', 12),
(31, 2012, 'Jack Reacher', 'Fostul investigator militar Jack Reacher (Tom Cruise) este pe urmele unui ucigas care a omorat sase oameni, fiecare dintr-un singur foc. Cand politistii sunt siguri ca au pus mana pe suspect, acesta refuza sa scoata o vorba, in schimb le da o hartie pe care scrie atat: "Aduceti-l pe Jack Reacher!". Asa incepe o cursa contracronometru pentru aflarea adevarului din spatele acestui caz, pe care Jack Reacher il va demonta piesa cu piesa luptandu-se cu un dusman la care nimeni nu se astepta.', 'crima', 'kK7y8Ou0VvM', 'http://cdn.songonlyrics.com/soundtracks/wp-content/uploads/2012/12/Jack-Reacher-Soundtrack.jpg', 15),
(32, 2012, 'Lawless (In afara legii)', 'Cei trei frati au condus o afacere ilegala, au iubit cu pasiune si s-au luptat sa se mentina pe linia de plutire in timp ce si-au vazut familia destramandu-se, afacerea tatalui lor intrand in faliment si lumea din jurul lor ruinandu-se sub povara crizei economice si a secetei.', 'crima', '4Zl7S1LaPMU', 'http://ecx.images-amazon.com/images/I/61SPV42gXkL._SL500_AA300_.jpg', 14),
(33, 22, 'test', 'jj', 'kk', 'll', 'pp', 0),
(34, 2, '', '', '', '', '', 0);
